version: '3.8'
services:
  nginx:
    container_name: reverse_proxy
    build: ./nginx/
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app
    restart: always

  back:
    container_name: backend
    build: ./back/
    
    privileged: true

    devices:
      - /dev/bus/usb:/dev/bus/usb
    
    ports:
      - "8000:8000"
    
    env_file:
      - .env
    
    volumes:
      - ./back/app:/app
      - ./back/archives:${ARCHIVE_FOLDER}
    
    networks:
      - app
    
    restart: always

  front:
    container_name: front
    build: ./front/
    ports:
      - "5000:5000"
    environment:
      - VITE_APP_URL=${APP_URL}:${APP_PORT}
    
    volumes:
      - ./front/src:/app/src
    networks:
      - app

    restart: always

networks:
  app: