version: '3.8'
services:
  nginx:
    container_name: reverse_proxy
    build: ./nginx/
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app
    restart: always

  back:
    container_name: backend
    build: ./back/
    ports:
      - "8000:8000"
    
    env_file:
      - .env
    
    volumes:
      - ./back/app:/app
      - ./back/archives:${ARCHIVE_FOLDER}
    
    networks:
      - app
    
    depends_on:
      - database
    
    restart: always

  database:
    image: mysql:latest
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    
    volumes:
      - ./db/scripts/:/docker-entrypoint-initdb.d
      - ./db/mysql:/var/lib/mysql
    
    networks:
      - app

    restart: always

  front:
    container_name: front
    build: ./front/
    ports:
      - "5000:5000"
    environment:
      - VITE_APP_URL=${APP_URL}:${APP_PORT}
    networks:
      - app

    restart: always

networks:
  app: